SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[STP_TASK_READ]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
    drop procedure [dbo].[STP_TASK_READ]
GO


CREATE PROCEDURE STP_TASK_READ
	@NM_TASK VARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;

    
	SELECT SQ_TASK, NM_TASK, DS_TASK 
    FROM TB_TASK

END
GO
